name: Check

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pnpm
        id: pnpm-install
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.5.0
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

